# Generated by Django 5.1.1 on 2024-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_lancamento_descricao_alter_lancamento_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
