# Generated by Django 5.1.1 on 2024-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_lancamento_descricao_alter_lancamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(),
        ),
    ]
